### ISSUE TITLE
[4.0] Scaffold for polyrepo generates `tsconfig.build.json` but looks for `tsconfig.mjs.json`

### ISSUE THREAD

**Issue by svallory** [milesj/packemon#244]
To reproduce, scaffold a polyrepo then run `packemon pack --declaration`

```
packemon pack --declaration

 ERROR

 Command failed with exit code 1: tsc --declaration --declarationDir mjs --declarationMap --emitDeclarationOnly
 --project tsconfig.mjs.json
 error TS5058: The specified path does not exist: 'tsconfig.mjs.json'.

 STACK TRACE

    at makeError (file:///Users/svallory/Library/pnpm/global/5/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/svallory/Library/pnpm/global/5/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Artifact.buildTypes (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/nod
e_modules/packemon/mjs/Artifact.mjs:134:5)
    at async Promise.all (index 1)
    at async Artifact.build (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_mod
ules/packemon/mjs/Artifact.mjs:59:5)
    at async file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_modules/packemon/mj
s/Package.mjs:48:9
    at async Promise.all (index 1)
    at async Package.build (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_modu
les/packemon/mjs/Package.mjs:44:5)
    at async Packemon.build (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_mod
ules/packemon/mjs/Packemon.mjs:29:7)
    at async PackCommand.build (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_
modules/packemon/mjs/commands/Build.mjs:24:5)
    at async PackCommand.pack (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_m
odules/packemon/mjs/commands/Build.mjs:67:5)
    at async PackCommand.run (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_mo
dules/packemon/mjs/commands/Pack.mjs:9:5)
    at async Program.runAndRender (file:///Users/svallory/Library/pnpm/global/5/.pnpm/@boost+cli@5.0.0_ink@4.4.1_react@1
8.2.0_typescript@5.3.3/node_modules/@boost/cli/mjs/Program.mjs:464:24)
    at async Program.run (file:///Users/svallory/Library/pnpm/global/5/.pnpm/@boost+cli@5.0.0_ink@4.4.1_react@18.2.0_typ
escript@5.3.3/node_modules/@boost/cli/mjs/Program.mjs:288:18)
    at async Program.runAndExit (file:///Users/svallory/Library/pnpm/global/5/.pnpm/@boost+cli@5.0.0_ink@4.4.1_react@18.
2.0_typescript@5.3.3/node_modules/@boost/cli/mjs/Program.mjs:307:22)
    at async run (file:///Users/svallory/Library/pnpm/global/5/.pnpm/packemon@4.0.0_typescript@5.3.3/node_modules/packem
on/mjs/bin.mjs:39:3)
```

**Comment by milesj** [comment]
Fixed
